repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        exclude: ^(enc|doc|src/data)
        args: [
          "--fix",
          "--config",
          #"./ruff.toml"
          "./ruff_temp.toml"
          ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: >
            (?x)^(
                src/settings/ahid_settings_default.toml|
                src/settings/constants.toml
            )$
        args: [
          "-I",
          ".codespellignore",
          "--write-changes",
        ]